### ISSUE TITLE
First Group Project!

### ISSUE THREAD

**Issue by snamini** [snamini/Our-First-Team-Project-#1]
# **Project Title:**
TBD

## **Team Members**
Talia
Kim
Sabrina
Fernando

## **Project Description**
A source used to connect users to contribute to a philanthropic project based on volunteer opportunities in their area. 

## **Sketch of Final Product**
-Movie as the jumbotron
-Website description
-form to submit filters for the volunteer API
-form to submit your passion project (If we have time)
-Maps (search results pop up in maps)
Volunteer Match API
Google Maps API

## **Rough Breakdown of Task**
Will work on this

#  **Timeline Goals**

**1. Before Wednesday:** 
- [x] research API's
- [x] Think of 5 Names Each
- [x] Find Motto With Name 
- [x] Do Train Homework Assignment

**2. In Class Wednesday :**
- [x] Find Website Theme
- [ ] Psuedo Code the Project

**3. Before Saturday Class:**
- [ ] Finish Psuedo Code
- [ ] Have a list of typed out questions to ask in class

### TO-DO ITEMS
****TOP PRIORITY
- [ ] Create pseudo-code to connect VolunteerMatch API to search 
- [ ] Create Psuedo-Code to connecting search results to our MAP API (Need drop pins correlated to search results)

step 1: jquery ajax call  to the volunteer api with javascript

step 2: take that data and use the google map library to put it on the map

*****Last Priority
- [ ] Find cover photo

- [ ] Create Description Section

- [ ] Create "Our Partners" Section and add links to their pages with their logo

**4. In Class Saturday:**
- [ ] Review Psuedo Code with each other
- [ ] Have all questions answered!

**5. Before Monday's Class:**
- [ ] Finish 75% of code

**6. In Class Monday:**
- [ ] Keep working on code together

**7. Tuesday Night:**
- [ ] Group Meeting

**8. Before Wednesday's Class:**
- [ ] Have code FINISHED
- [ ] Group meeting to put together code

**9. In class Wednesday:**
- [ ] Group Presentation and Powerpoint

**10. Before Saturday's Class:**
- [ ] Prepare to give the best damn speech ever!
